//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Destructurama.Attributed;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace UTG.Models.TerminalModels
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "mmlresponse")]
    public class mmlresponse
    {
        [XmlElement("m4")]
        public List<m4> m4 { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class m4
    {
        private m4AO AOField;
        private m4K9 k9Field;

        private m4M7 m7Field;

        private m4P7 p7Field;

        private m4w8 w8Field;

        public m4AO AO
        {
            get
            {
                return this.AOField;
            }
            set
            {
                this.AOField = value;
            }
        }

        /// <remarks/>
        public m4K9 k9
        {
            get
            {
                return this.k9Field;
            }
            set
            {
                this.k9Field = value;
            }
        }

        /// <remarks/>
        public m4M7 m7
        {
            get
            {
                return this.m7Field;
            }
            set
            {
                this.m7Field = value;
            }
        }

        /// <remarks/>
        public m4P7 P7
        {
            get
            {
                return this.p7Field;
            }
            set
            {
                this.p7Field = value;
            }
        }

        /// <remarks/>
        public m4w8 w8
        {
            get
            {
                return this.w8Field;
            }
            set
            {
                this.w8Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class m4AO
    {
        private string[] blField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BL")]
        public string[] BL
        {
            get
            {
                return this.blField;
            }
            set
            {
                this.blField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class m4K9
    {

        private string u8Field;

        private string w7Field;

        private string x1Field;

        private string j3Field;

        private string a3Field;

        private string X9Field;
        /// <summary>
        /// Last Four
        /// </summary>
        public string X9
        {
            get
            {
                return this.X9Field;
            }
            set
            {
                this.X9Field = value;
            }
        }
        /// <remarks/>
        [LogMasked(ShowFirst = 4, PreserveLength = true)]
        public string U8
        {
            get
            {
                return this.u8Field;
            }
            set
            {
                this.u8Field = value;
            }
        }

        /// <remarks/>
        public string w7
        {
            get
            {
                return this.w7Field;
            }
            set
            {
                this.w7Field = value;
            }
        }

        /// <remarks/>
        public string x1
        {
            get
            {
                return this.x1Field;
            }
            set
            {
                this.x1Field = value;
            }
        }

        /// <remarks/>
        public string j3
        {
            get
            {
                return this.j3Field;
            }
            set
            {
                this.j3Field = value;
            }
        }

        /// <remarks/>
        public string A3
        {
            get
            {
                return this.a3Field;
            }
            set
            {
                this.a3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class m4M7
    {

        private string m5Field;

        private string m6Field;

        private string e4Field;

        private string d3Field;

        /// <remarks/>
        public string m5
        {
            get
            {
                return this.m5Field;
            }
            set
            {
                this.m5Field = value;
            }
        }

        /// <remarks/>
        public string m6
        {
            get
            {
                return this.m6Field;
            }
            set
            {
                this.m6Field = value;
            }
        }

        /// <remarks/>
        public string E4
        {
            get
            {
                return this.e4Field;
            }
            set
            {
                this.e4Field = value;
            }
        }

        /// <remarks/>
        public string D3
        {
            get
            {
                return this.d3Field;
            }
            set
            {
                this.d3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class m4P7
    {

        private uint idField;

        /// <remarks/>
        public uint ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class m4w8
    {

        private string BPField;

        /// <remarks/>
        public string BP
        {
            get
            {
                return this.BPField;
            }
            set
            {
                this.BPField = value;
            }
        }
    }
}
