//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Destructurama.Attributed;
using System.Xml.Serialization;
namespace UTG.Models.OPIModels
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TokenResponse
    {

        private string sequenceNoField;

        private string transTypeField;

        private string respCodeField;

        private string respTextField;

        private TokenResponseCardInfo[] cardInfoField;

        private string[] textField;

        /// <remarks/>
        public string SequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }

        /// <remarks/>
        public string TransType
        {
            get
            {
                return this.transTypeField;
            }
            set
            {
                this.transTypeField = value;
            }
        }

        /// <remarks/>
        public string RespCode
        {
            get
            {
                return this.respCodeField;
            }
            set
            {
                this.respCodeField = value;
            }
        }

        /// <remarks/>
        public string RespText
        {
            get
            {
                return this.respTextField;
            }
            set
            {
                this.respTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CardInfo")]
        public TokenResponseCardInfo[] CardInfo
        {
            get
            {
                return this.cardInfoField;
            }
            set
            {
                this.cardInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TokenResponseCardInfo
    {

        private string recordField;

        private string issuerIdField;

        private string pANField;

        private string transTokenField;

        /// <remarks/>
        public string Record
        {
            get
            {
                return this.recordField;
            }
            set
            {
                this.recordField = value;
            }
        }

        /// <remarks/>
        public string IssuerId
        {
            get
            {
                return this.issuerIdField;
            }
            set
            {
                this.issuerIdField = value;
            }
        }

        /// <remarks/>
        [LogMasked(ShowLast = 4, PreserveLength = true)]
        public string PAN
        {
            get
            {
                return this.pANField;
            }
            set
            {
                this.pANField = value;
            }
        }

        /// <remarks/>
        [LogMasked(ShowFirst = 4, PreserveLength = true)]
        public string TransToken
        {
            get
            {
                return this.transTokenField;
            }
            set
            {
                this.transTokenField = value;
            }
        }
    }
}