//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Destructurama.Attributed;
using System.Xml.Serialization;
namespace UTG.Models.OPIModels
{
    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TokenRequest
    {

        private string sequenceNoField;

        private string transTypeField;

        private string transDateTimeField;

        private string siteIdField;

        private string industryCodeField;

        private string proxyInfoField;

        private string pOSInfoField;

        private TokenRequestCardInfo[] cardInfoField;

        /// <remarks/>
        public string SequenceNo
        {
            get
            {
                return this.sequenceNoField;
            }
            set
            {
                this.sequenceNoField = value;
            }
        }

        /// <remarks/>
        public string TransType
        {
            get
            {
                return this.transTypeField;
            }
            set
            {
                this.transTypeField = value;
            }
        }

        /// <remarks/>
        public string TransDateTime
        {
            get
            {
                return this.transDateTimeField;
            }
            set
            {
                this.transDateTimeField = value;
            }
        }

        /// <remarks/>
        public string SiteId
        {
            get
            {
                return this.siteIdField;
            }
            set
            {
                this.siteIdField = value;
            }
        }

        /// <remarks/>
        public string IndustryCode
        {
            get
            {
                return this.industryCodeField;
            }
            set
            {
                this.industryCodeField = value;
            }
        }

        /// <remarks/>
        public string ProxyInfo
        {
            get
            {
                return this.proxyInfoField;
            }
            set
            {
                this.proxyInfoField = value;
            }
        }

        /// <remarks/>
        public string POSInfo
        {
            get
            {
                return this.pOSInfoField;
            }
            set
            {
                this.pOSInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CardInfo")]
        public TokenRequestCardInfo[] CardInfo
        {
            get
            {
                return this.cardInfoField;
            }
            set
            {
                this.cardInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TokenRequestCardInfo
    {

        private string recordField;

        private string transTokenField;

        private string PANField;

        private string expiryDateField;

        /// <remarks/>
        public string Record
        {
            get
            {
                return this.recordField;
            }
            set
            {
                this.recordField = value;
            }
        }

        /// <remarks/>
        [LogMasked(ShowFirst = 4, PreserveLength = true)]
        public string TransToken
        {
            get
            {
                return this.transTokenField;
            }
            set
            {
                this.transTokenField = value;
            }
        }
   
        /// <remarks/>
        [LogMasked(ShowLast = 4, PreserveLength = true)]
        public string PAN
        {
            get
            {
                return this.PANField;
            }
            set
            {
                this.PANField = value;
            }
        }

        /// <remarks/>
        [LogMasked(Text = "*", PreserveLength = true)]
        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
    }
}
